### ISSUE TITLE
version can not used with HACS

### ISSUE THREAD

**Issue by AKerschbaum** [jovana/remko-heat-pump#3]
I tried to install the integration via HACS.
I was not able to download it. I got this error message:
"The version ee446e2 for this integration can not used with HACS"

Any advice? thx

![grafik](https://github.com/user-attachments/assets/70f97bbd-ade2-4a70-ad3f-d9807bf84dc0)

**Comment by jovana** [comment]
Installation using HACS is not support. Check this: https://github.com/jovana/remko-heat-pump/wiki#installing-remko-heatpump-sensors-into-home-assistant
