### ISSUE TITLE
The version ee446e2 for this integration can not be used with HACS.

### ISSUE THREAD

**Issue by NoMaamBtl** [jovana/remko-heat-pump#6]
When i try to download Remko Heatpump Sensor Integration via HACS. I've got this Error: The version ee446e2 for this integration can not be used with HACS.
Core 2024.12.5
Supervisor 2024.12.0
Operating System 14.1
Frontend 20241127.8
Home Assistant Green

**Comment by jovana** [comment]
Hi, there is no hacs support. Instructions how to install you find on the readme.md.
